#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Exodus\Config\ConfigFile;
use Exodus\Config\Templates;
use Exodus\Command\BootstrapCommand;
use Exodus\Command\MakeMigrationCommand;
use Exodus\Command\MigrateCommand;
use Exodus\Helpers\PathBuilder;
use Exodus\Database\Adapter\Factory as AdapterFactory;

use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;
use Symfony\Component\Console\Output\ConsoleOutput;

$path_builder = new PathBuilder();

// Instantiate object for exodus.yml
$config_file = new ConfigFile(
    $path_builder->build([getcwd(), 'exodus.yml']),
    new AdapterFactory()
);

// Instantiate object for the templates/ folder
$templates = new Templates($path_builder->build(['.', 'templates']));

// Register Commands
$application = new Application('Exodus Migrations CLI');
$application->add(new BootstrapCommand($config_file, $templates));
$application->add(new MakeMigrationCommand($config_file, $templates));
$application->add(new MigrateCommand($config_file));

try {

    $application->run();

} catch (\Exception $e) {

    $output = new ConsoleOutput();
    $output->writeln($e->getMessage());
}